//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdrakhmanovPCConfigurator.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Component
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Parametrs { get; set; }
        public Nullable<int> Parent_Id { get; set; }
    }
}
