//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbdrakhmanovPCConfigurator.WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinishedPC
    {
        public int IdFinishedPC { get; set; }
        public string NameFinishedPC { get; set; }
        public string Components { get; set; }
    }
}
